### ISSUE TITLE
Separate all the variables from index.scss 

### ISSUE THREAD

**Issue by anmoljhamb** [anmoljhamb/portfolio#5]
Separate all the variables from `index.scss` and put them in a file named `variables.scss`. So the file "index.scss" doesn't need to imported in all of the files to get access to those variables.

**Comment by Pavan-Nambi** [comment]
@anmoljhamb hey can u review is that's all should be done or any other chnages?

**Comment by Pavan-Nambi** [comment]
nice portfolio btw gives original feel didn't see this type of model/design before

**Comment by anmoljhamb** [comment]
Thanks! Also, I have a suggestion. Next time you contribute, you should make a separate branch for that particular issue, and then apply for a pull request.
